### ISSUE TITLE
class CanonicalUrlProcess extends AbstractCanonicalUrlProcess but AbstractCanonicalUrlProcess is missing

### ISSUE THREAD

**Issue by VladiCz** [hryvinskyi/magento2-seo-canonical-amasty-shop-by-brand#1]
class CanonicalUrlProcess extends AbstractCanonicalUrlProcess but AbstractCanonicalUrlProcess is not part of the Hryvinskyi\SeoCanonicalFrontend module

**Comment by hryvinskyi** [comment]
Hi @VladanZ,

This module is part for catalog category canonical
Here metapackage for this https://github.com/hryvinskyi/magento2-seo-canonical-pack 
You need to install this metapackage for correctly works
